### ISSUE TITLE
New WINC1500 firmware 19.7.7

### ISSUE THREAD

**Issue by awatterott** [arduino-libraries/WiFi101-FirmwareUpdater-Plugin#64]
Hello,
There is a new firmware v19.7.3 for the WINC1500 available.

Release Notes:
https://www.microchip.com/content/dam/mchp/documents/WSG/ProductDocuments/ReleaseNotes/ATWINC15X0_Software_Release_Notes_v19.7.3.pdf

OTA-Firmware (firmware for the updater tool is included in the latest examples of the Microchip Studio):
https://www.microchip.com/content/dam/mchp/documents/WSG/ProductDocuments/SoftwareLibraries/Firmware/ATWINC1500_FW_19_7_3_02NOV2020.zip

**Comment by awatterott** [comment]
The latest firmware is now v19.7.6.

Release Notes:
https://ww1.microchip.com/downloads/aemDocuments/documents/WSG/ProductDocuments/ReleaseNotes/WINC150019.7.6releasenote.pdf

Firmware:
https://github.com/Microchip-MPLAB-Harmony/wireless_wifi/tree/master/utilities/wifi/winc/files/winc1500

**Comment by awatterott** [comment]
The latest firmware is 19.7.7

Firmware:
https://github.com/Microchip-MPLAB-Harmony/wireless_wifi/tree/master/utilities/wifi/winc/files/winc1500/19.7.7

Release Notes:
https://github.com/Microchip-MPLAB-Harmony/wireless_wifi/blob/master/utilities/wifi/winc/files/winc1500/19.7.7/WINC1500_REL_NOTES.pdf

**Comment by aentinger** [comment]
/cc @umbynos

Worth pinging him again :wink:

**Comment by umbynos** [comment]
Hello @awatterott,
Unfortunately this tool is no longer maintained, the new one is [arduino-fwuploader](https://github.com/arduino/arduino-fwuploader). This is the tool is bundled in the IDE2.
But sadly, support for MKR1000 (which has module WINC1500) has been dropped in https://github.com/arduino/arduino-fwuploader/pull/209 (because the board reached EOL).
I'm sorry, but I think this request will not be completed
